-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 20, 2024 at 05:40 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `browsehunt`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin_master`
--

CREATE TABLE `admin_master` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `type` tinyint(4) NOT NULL DEFAULT 2,
  `organisation_id` int(11) NOT NULL,
  `profile_image` varchar(255) DEFAULT NULL,
  `last_logged_in` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

--
-- Dumping data for table `admin_master`
--

INSERT INTO `admin_master` (`id`, `name`, `email`, `password`, `type`, `organisation_id`, `profile_image`, `last_logged_in`, `created_at`) VALUES
(1, 'Shivam', 's@mobavenue.com', '827ccb0eea8a706c4c34a16891f84e7b', 1, 1, 'https://ik.imagekit.io/gku4adhog/thevadapav/Users/mandar.png?updatedAt=1701333601657', NULL, '2023-11-23 18:30:13'),
(2, 'Vatsal', 'vatsal.shah@mobavenue.com', '08a8b71d3762df7ff3eb422bbcf623f5', 2, 1, 'https://ik.imagekit.io/gku4adhog/thevadapav/Users/vatsal.jpg?updatedAt=1701333601653', NULL, '2023-11-29 18:49:16'),
(4, 'Rhea', 'rhea.crasto@mobavenue.com', '08a8b71d3762df7ff3eb422bbcf623f5', 2, 1, 'https://ik.imagekit.io/gku4adhog/thevadapav/Users/user.png?updatedAt=1701333712775', NULL, '2023-11-30 14:06:12'),
(5, 'Tanisha', 't@mobavenue.com', '827ccb0eea8a706c4c34a16891f84e7b', 1, 1, 'https://ik.imagekit.io/w8iaqu9bf/cat/glasses.gif?updatedAt=1707841337830', NULL, '2024-02-14 18:47:57'),
(6, 'Manika', 'manika@mobavenue.com', '08a8b71d3762df7ff3eb422bbcf623f5', 2, 1, NULL, NULL, '2024-02-14 18:54:02');

-- --------------------------------------------------------

--
-- Table structure for table `articles`
--

CREATE TABLE `articles` (
  `id` int(11) NOT NULL,
  `category_id` int(11) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `description1` text DEFAULT NULL,
  `description2` text DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `read_time` int(11) DEFAULT NULL,
  `meta_title` varchar(255) DEFAULT NULL,
  `meta_description` varchar(255) DEFAULT NULL,
  `meta_keywords` varchar(255) DEFAULT NULL,
  `author_id` int(11) DEFAULT NULL,
  `article_date` date DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

--
-- Dumping data for table `articles`
--

INSERT INTO `articles` (`id`, `category_id`, `title`, `url`, `description1`, `description2`, `image`, `read_time`, `meta_title`, `meta_description`, `meta_keywords`, `author_id`, `article_date`, `created_at`) VALUES
(1, 1, 'Know Everything About Google Cloud Platform', 'what-is-google-cloud-platform', 'Cloud computing is not just hype in today\'s evolving digital world; it has become essential. One of the major players in this arena is Google Cloud Platform (GCP), offering various cloud computing services, including computing, storage, AI, machine learning, and more. What\'s interesting is that GCP utilizes the same robust infrastructure as Google\'s popular end-user products like Google Search, Gmail, and YouTube.', 'GCP stands out for its powerful data analytics and Machine Learning (ML) capabilities. Through services like BigQuery and AutoML, businesses can innovate and grow effortlessly, keeping up with the fast-paced digital world. But what does all this mean for businesses, and why should one care about GCP? This article talks about the advantages of GCP and why it\'s gaining significance in technology and business.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/1_oNwAtVjx0.jpg?updatedAt=1713444311408', 2, ' Google Cloud Platform: Meaning and Importance', 'Explore the reasons behind Google Cloud Platform\'s supremacy in the cloud computing sector and its role in scaling and enhancing your business operations.', 'Google Cloud Platform, what is Google Cloud platform', 1, '2024-02-22', '2024-04-18 10:41:33'),
(2, 1, 'The Ultimate List of Data Security Tools and Practices', 'data-security-tools-and-practices', 'Today\'s digital world requires a deep understanding of data security, where the internet can also be helpful and risky for your data. Thus, people and businesses must use robust tools and methods to keep their data safe.', 'This guide will explain why data security is crucial, what tools you can use, and the best habits to keep your digital life safe. When you finish reading, you\'ll know how to protect your online information well.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/2_w4royypSum.jpg?updatedAt=1713444250609', 3, 'A Comprehensive Guide to Data Security Tools and Practices', 'This detailed guide on data security outlines the necessary tools and best practices for safeguarding your data from cyber threats and breaches.', 'data security, what is data security, data security tools, data security practices', 2, '2024-02-23', '2024-04-18 10:43:40'),
(3, 2, '5 Best Business Management Degree Programs in India', 'best-business-management-degree-programs', 'In recent decades, India has experienced rapid economic growth, driving an increased need for proficient business professionals. Consequently, numerous academic institutions have surfaced, providing tailored degree programs in business management to cater to this demand.', 'These programs are designed to empower young individuals with the essential knowledge and skills required to thrive in the ever-evolving business landscape. Explore India\'s premier business management degree programs, aspired by students and employers alike.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/3_C94iIdjqA6.jpg?updatedAt=1713444252103', 3, '5 Best Business Management Degree Programs in India for 2024', 'Top 5 business management degree programs in India for 2024. 1. Indian Institute of Management (IIM) • 2. Indian School of Business (ISB), and more.', 'Business Management Degree, Degree Programs, Degree Programs in India for 2024, Management Degree, Business Management', 3, '2024-02-24', '2024-04-18 10:46:11'),
(4, 2, 'Beginner\'s Guide to Top Digital Marketing Courses 2024', 'digital-marketing-courses-for-beginners', 'Are you considering changing jobs or simply aiming to improve your tech skills? If that\'s the case, you might find digital marketing to be a promising avenue. It\'s an expanding field packed with learning opportunities.', 'However, finding the best one can be daunting with the abundance of available online digital marketing courses. This guide is here to simplify things for you. It will shed light on digital marketing and highlight some excellent courses tailored for beginners in 2024.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/4_Zh9avXCqCP.jpg?updatedAt=1713444250842', 2, 'Top Digital Marketing Courses for Beginners in 2024', ' Ready to launch your digital marketing career? Find the top beginner digital marketing courses for 2024 and start mastering your skills now!', 'digital marketing courses, digital marketing, digital marketing course', 4, '2024-02-25', '2024-04-18 10:47:44'),
(5, 2, 'Top 5 Animation Courses Available in India for 2024', '5-best-animation-courses', 'Animation is a dynamic and enthralling realm that attracts creative individuals with a tech-savvy edge, all striving to infuse narratives with vitality. Thanks to its booming entertainment industry and world-renowned IT landscape, India has emerged as a prime destination for animation education, fostering talent and driving innovation in this vibrant sector.', 'As advanced technologies and digital platforms continue to evolve, the demand for skilled animators in India is rising. Therefore, selecting the correct educational path has become imperative. Explore the top animation courses in India designed for 2024.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/5_muddzidA2m.jpg?updatedAt=1713444326740', 2, '5 Best Animation Courses Available in India for 2024', 'Discover the top 5 animation courses and universities in India for 2024. 1. National Institute of Design (NID) • 2. Whistling Woods International (WWI) & more.', 'animation courses,  Animation Courses in India, best animation courses', 5, '2024-02-26', '2024-04-18 10:49:43'),
(6, 3, 'Cataract Surgery: Causes, Symptoms, and Prevention', 'understanding-cataract-surgery-causes-symptoms-prevention', 'Cataracts impact millions annually and stand as a primary cause of global blindness. Simply put, a cataract is clouding the eye\'s typically clear lens. For individuals grappling with cataracts, their sight mimics that of someone straining to see through a veil of mist or frost.', 'Cataract sufferers may struggle reading or driving in dim light, impacting their daily routines. Treatment is crucial. We aim to guide those seeking insight into this condition, covering causes, symptoms, and cataract-removal surgery.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/6_BTGlqNKP5t.jpg?updatedAt=1713444326747', 3, ' Know Cataract Surgery: Causes, Symptoms, and Prevention', 'Know about cataracts in detail. Understanding the causes, symptoms, and prevention is vital before having typically safe and effective cataract surgery.', 'cataract, cataract surgery, symptoms of cataract', 6, '2024-02-27', '2024-04-18 10:51:35'),
(7, 4, 'Exploring the Advantages of Coworking Spaces for Digital Nomads', 'benefits-of-coworking-spaces-for-digital-nomads', 'The concept of coworking spaces has gained traction in the last decade, aligning with the surge of digital nomadism and remote work trends. These spaces provide a collaborative, productive, and communal office-like setting for freelancers, entrepreneurs, and startups. In this blog, we delve into the numerous advantages of coworking spaces, especially for digital nomads desiring flexibility without sacrificing professionalism.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/7__8-2MyX1_v.jpg?updatedAt=1713444251297', 3, 'Advantages of Coworking Spaces for Modern Digital Nomads', 'Discover the advantages of coworking spaces for digital nomads, including nurturing creativity, fostering innovation, and enhancing work-life balance.', 'coworking spaces, spaces for modern business, digital nomads, advantages of coworking spaces', 7, '2024-02-28', '2024-04-18 10:58:13'),
(8, 1, 'Know These 7 Cybersecurity Trends 2024 for Digital Safety', 'cybersecurity-trends', 'In the digital world, cybersecurity has become indispensable. With each passing year, we witness the emergence of new trends and strategies as cyberspace evolves. It\'s no longer just about safeguarding our data; cybersecurity in 2024 has grown more detailed and widespread than ever before. This year, attention is directed towards several crucial areas, ranging from Generative AI to the advancement of Quantum Computing.', 'You may ask, what is cybersecurity? It entails protecting systems, networks, and software from digital assaults. Generally, these cyberattacks target sensitive information to access, alter, or destroy it, extort money from users, or disrupt regular business operations. But here\'s the thing: making cybersecurity effective is challenging because there are more gadgets than people, and attackers are constantly coming up with new tricks.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/8_j6RRfJKMsO.jpg?updatedAt=1713444250752', 3, 'Top 7 Cybersecurity Trends 2024 You Need to Know', 'These cybersecurity trends for 2024 will show why cybersecurity is essential, what it aims to achieve, and how it protects against digital threats', 'Cybersecurity, cybersecurity courses, what is cybersecurity?, what are the three goals of cybersecurity?', 8, '2024-02-29', '2024-04-18 11:00:34'),
(10, 5, 'How to Select the Ideal Security Camera System for Your Home', 'how-to-choose-the-right-home-security-system', 'Owning a security camera system can significantly boost home safety. With many options available, choosing the right system depends on key factors. Homeowners investing in a security camera system should assess their requirements, home setup, and technology. Check out our ultimate guide for selecting your home\'s ideal security camera system.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/10_Nis3Mf__c.jpg?updatedAt=1713444309261', 2, 'How to Select the Right Home Security Camera System', 'Know how to navigate the fundamentals of selecting the ideal security camera system for your home. Before making a purchase, explore this blog for further insights.', 'security camera for home, security camera system, safety', 2, '2024-03-02', '2024-04-18 11:05:02'),
(11, 6, '10 Online Games for 2024 You Should Not Miss', 'popular-online-games', 'Every year, online gaming gains more popularity, with new titles launching monthly and the gaming world constantly evolving. Whether you are an experienced player or new to gaming, keeping up with the best online games is crucial.', 'In 2024, online gaming has evolved to cater to a global audience, offering immersive gameplay, stunning graphics, and competitive challenges that keep players engaged to play online games. This article overviews the top 10 online games captivating players worldwide.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/11_N7_bnCAen.jpg?updatedAt=1713444294426', 2, 'The Top 10 Online Games You Can\'t Miss in 2024', 'Your 2024 gaming list should definitely include these 10 online games. • 1. Roblox • 2. Minecraft • 3. Among Us • 4. Valorant • 5. Fortnite and more', 'online games, play online games, online games to play, best online games', 3, '2024-03-03', '2024-04-18 11:06:45'),
(12, 4, '6 Call Center Trends to Watch Out for in 2024', 'call-center-trends', 'Today, delivering effective and efficient customer service has become essential for the success of any brand. For decades, the call center industry has played an indispensable role in this regard, connecting businesses with their customers and ultimately contributing to brand growth and prosperity. However, meeting customer expectations presents a dynamic challenge with a constantly evolving market.', 'As businesses strive to innovate their call center strategies, this blog post discusses emerging trends reshaping customer service in 2024. From advancements in AI to integrating remote workforce solutions, these trends promise to bring about exciting developments that aim to improve customer satisfaction and streamline business operations.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/12_XscNvdUGTr.jpg?updatedAt=1713444281918', 2, 'Top 6 Call Center Trends That Will Shape 2024', 'Transform your customer experience strategy with these Call Center Trends 2024, offering insights into the newest industry advancements and best practices', 'call center', 4, '2024-03-04', '2024-04-18 11:09:29'),
(13, 4, 'The Tech-Driven Evolution of Employee Training & Development', 'employee-training-and-development', 'A successful company relies on its employees, who are like engines powering a successful company. To keep them running smoothly, they need regular tuning and maintenance. Just as a well-maintained engine can improve performance and efficiency, ongoing training and development can enhance employee skills and keep them engaged.', 'Traditional training practices worked before, but today, things have changed. It\'s time to see how technology is changing the game in employee training and development and how new platforms are shaping to help employees grow in today\'s workplaces.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/13_6tGVGe6pi3.jpg?updatedAt=1713444281836', 3, 'Technological Trends in Employee Training & Development', 'Revolutionize employee training and development strategies with the latest technological trends and gain a competitive edge in the modern workplace', 'employee training and development', 8, '2024-03-05', '2024-04-18 11:12:29'),
(14, 4, 'Decoding Customer Data Analysis in Digital Marketing', 'customer-data-analysis', 'The gap between online content consumption and consumer behavior is narrowing rapidly in the fast-evolving digital market. Consequently, traditional market research is evolving into advanced customer data analysis. ', 'While businesses increasingly adopt this approach to customize campaigns and forecast consumer needs, many face challenges in maximizing its benefits. This guide educates them on a roadmap for effectively leveraging customer data, elevating marketing strategies, and staying agile in the dynamic digital environment.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/14_77dKT8sMy-.jpg?updatedAt=1713444282360', 3, 'Elevate Your Digital Marketing with Customer Data Analysis', 'Unlock the secrets of successful digital marketing with advanced customer data analysis techniques, driving higher ROI and business growth', 'customer data analysis, digital marketing', 4, '2024-03-06', '2024-04-18 11:14:15'),
(15, 5, 'Smarter Luxurious Solutions for Businesses & Homes', 'smarter-luxurious-solutions-for-businesses-and-homes', 'In the dynamic realm of contemporary living, the concept of luxury undergoes continuous evolution. In 2024, luxury is redefined not by opulence and excess but by efficiency and ingenuity. Individuals strive for inventive solutions to simplify operations and elevate convenience, whether in lifestyle choices or business practices.', 'Recent technological progress has enabled the convergence of efficiency and luxury. Join me in uncovering inventive solutions that are revolutionizing business and residential environments.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/15_VlZ3KyOOe.jpg?updatedAt=1713444310435', 3, 'Luxurious Ease: Tailored Solutions for Businesses and Homes', 'Discover new ways to enhance efficiency and luxury in businesses and homes, like smart automation, eco-friendly practices, seamless AI integration, and more.', 'smart solutions, luxurious solution, business aesthetic, business interior, home interior, interior', 6, '2024-03-07', '2024-04-18 11:16:18'),
(16, 1, 'Best Sales Software and Penetration Testing Services', 'best-sales-software-penetration-testing-services', 'In today\'s digital era, excelling in online sales and safeguarding your software from cyber threats are paramount. Sales professionals, software developers, and IT managers always seek creative strategies to enhance performance and fortify their digital landscape.\r\n', 'In today\'s market, being competitive and secure requires a grasp of popular sales software and the significance of penetration testing services.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/16_6232X7JPii.jpg?updatedAt=1713444311895', 3, 'Best Sales Software & Penetration Testing Services in 2024', 'Discover leading sales software and top-tier penetration testing services, including HubSpot Sales, Slack, Outreach, Metasploit, Nessus, Leadfeeder, and more.', 'best sales software, penetration testing services', 7, '2024-03-08', '2024-04-18 11:18:26'),
(17, 3, 'Advances in Healthcare, Real Estate & Manufacturing Industries', 'revolutionization-in-healthcare-real-estate-manufacturing', 'In the present era, rapid innovation is reshaping various industries. Whether it\'s healthcare saving lives, real estate fostering community connections, or manufacturing driving consumer culture, every sector is undergoing transformative changes, propelling them towards a new era of efficiency and effectiveness.', 'Next, we\'ll focus on the impressive innovations reshaping diverse sectors. We will focus on the transformative progress in healthcare, real estate, and manufacturing.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/17_Isj9RrPzv.jpg?updatedAt=1713444312022', 2, ' Revolutionization in Healthcare, Real Estate & Manufacturing', 'Discover the evolving landscape of healthcare, real estate, and manufacturing industries, revealing crucial trends and innovations fueling sector expansion.', 'healthcare, real estate, manufacturing', 8, '2024-03-09', '2024-04-18 11:20:04'),
(18, 4, '5 Strategic Approaches for Business Growth in 2024', 'strategies-for-business-growth', 'In 2024, businesses constantly look for ways to grow and succeed in an ever-changing world. They face digital transformations, uncertain markets, and ongoing innovation, which present opportunities and challenges. At this point, strategic planning and adaptability become crucial for surviving and prospering in this constantly changing environment.', 'But what\'s being strategic in such an evolving world? This blog discusses how successful businesses use technology and innovative strategic planning to turn challenges into opportunities and why it is crucial to survive and thrive in today\'s fast-changing business world.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/18_bGrLRdgdcb.jpg?updatedAt=1713444162813', 3, '5 Essential Strategies for Business Growth in 2024', 'Gain a competitive edge in 2024 with these 5 key strategies for business growth. 1. Understand Your Market • 2. SMART Goals • 3. Technology  and more', 'strategies for business growth, how to grow business', 5, '2024-03-10', '2024-04-18 11:21:41'),
(19, 4, 'Boosting Efficiency: Industrial Machines\' Impact in India', 'industrial-machines-enhance-work-efficiency', 'In the dynamic landscape of today\'s industries, business operations are undergoing significant changes, particularly in the manufacturing and industrial domains. Central to this evolution are the industrial machines that drive progress.', 'These essential tools have revolutionized production processes, enhancing efficiency and boosting productivity. This article delves into the pivotal role of industrial machines in driving business growth, amplifying work efficiency in modern industries, and shaping the future landscape of sectors in India.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/19_QdmVg36oY9.jpg?updatedAt=1713444308809', 3, ' Boosting Efficiency Across India with Industrial Machinery', 'Discover the role of industrial machinery in enhancing efficiency. Know the influence of intelligent sensors and IoT technology on industrial effectiveness.', 'increase business efficiency', 2, '2024-03-11', '2024-04-18 11:23:16'),
(20, 7, 'Office Cleaning Jobs: Earn $43/HR Without Any Experience', 'dollar-43-per-hr-office-cleaning-jobs-with-no-experience', 'Office cleaning jobs seem like routine tasks that never end. But if you look closer, you will see it is a growing industry with exciting work and many benefits. Whether you\'re starting your career, thinking of a change, or curious about cleaning, this blog shows you the potential of office cleaning services.', 'Whether you are starting your career, thinking about a switch, or curious about sanitation work, this blog aims to explore the potential of office cleaning jobs thoroughly. It will keep you engaged and informed, offering insights into the career advancement opportunities this essential role can provide.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/20_0qhRFh2GaW.jpg?updatedAt=1713444283187', 3, '$43/HR Office Cleaning Jobs: No Prior Experience Required', 'Start earning $43/hour for office cleaning jobs without experience, and take pride in your role as you create hygienic and orderly workspaces', 'office cleaning jobs, office cleaning, office cleaning services', 1, '2024-03-12', '2024-04-18 12:06:53'),
(21, 7, 'Lucrative Circuit Board Assembly Roles: Entry-Level, $51/Hour, Equal Opportunity', 'dollar-51-hr-circuit-board-assembly-jobs-with-no-experience-needed', 'As technology becomes more integrated into our daily lives, the demand for skilled labor in tech manufacturing is rising. If you\'re looking for a fulfilling job that blends hands-on tasks with technical expertise and doesn\'t require prior experience, consider pursuing a role in circuit board assembly.', 'Circuit board assemblers are critical in producing electronic devices that facilitate our connectivity. Moreover, opportunities with a competitive salary of $51 per hour are available to both male and female candidates, regardless of prior experience.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/21_B7ArR3e86B.jpg?updatedAt=1713444161743', 2, '$51/HR Circuit Board Assembly Jobs: No Experience Needed', 'Entry-level circuit board assembly positions at $51 per hour are open to both men and women. Seize this opportunity to secure a job with just one click!', 'fresher jobs, jobs with no experience, jobs', 2, '2024-03-13', '2024-04-18 12:08:26'),
(22, 5, 'Two-Bedroom Apartments At Prime Location | From $350/Month', 'two-bedroom-apartments-at-prime-location', 'Are you searching for a two-bedroom apartment that seamlessly blends luxury, coziness, and convenience in a prime location? Look no further. You can now own a luxurious two-bedroom apartment at an affordable $350 per month in highly sought-after locations with unparalleled lifestyle benefits.\r\n', 'Prime location apartments, ideally situated amidst the pulse of city living, are coveted for their accessibility, convenience, and undeniable allure. Luxurious two-bedroom apartments in prime locations capture the attention of discerning renters seeking the perfect blend of sophistication and comfort.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/22_lelQ4SOOq8.jpg?updatedAt=1713444154156', 2, 'From $350/Month | Two-Bedroom Apartments At Prime Locations', 'Spacious living, modern kitchens, and spa-like baths await! Find your dream two-bedroom apartment in a prime location at just $350/Month!', 'house at prime locations, spacious homes, apartment', 4, '2024-03-14', '2024-04-18 12:10:09'),
(23, 7, '$51/HR Home Care Jobs with No Experience Required', 'hiring-for-home-care-jobs-with-no-experience-required', 'In a landscape of uncertainty and swift transformations, job seekers often yearn for a career path that promises stability, fulfillment, and a competitive salary. The home care sector stands out as a beacon of opportunity, empowering people to make a meaningful difference in the lives of others while cementing their financial security—all achievable even without prior experience.', 'Both men and women are discovering a fulfilling career path in the expanding home care realm. Within this sector, professionals offer assistance and companionship to individuals who require help with their day-to-day activities.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/23_UwFsJhoGUY.jpg?updatedAt=1713444152995', 2, '$51/HR Home Care Job with No Experience Required', 'Discover well-paying Home Care Jobs offering $51 per hour, open to both men and women. No prior experience is required. Join this lucrative opportunity today!', 'home care jobs, jobs without experience, high paying jobs', 3, '2024-03-15', '2024-04-18 12:11:54'),
(24, 7, 'The Promise of $51/HR Warehouse Packing Jobs: A Pathway to Opportunity for All', 'dollar-51-warehouse-packaging-jobs', 'In today\'s fast-paced world, where the job market can often seem daunting and competitive, stumbling upon an opportunity that offers both fair compensation and accessibility is rare. Such is the allure of warehouse packing jobs, where the promise of $51 per hour beckons individuals from all walks of life, regardless of prior experience or gender. Let us look into this enticing prospect and explore how it could lead to a brighter future for many.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/24_APRYgy42Gw.jpg?updatedAt=1713444158891', 2, 'Warehouse Packaging Job $51/hr: Opportunities Open For All', 'Check out these new opportunities for warehouse packaging jobs that offer $51/hr. This offer doesn’t require any other experience and is open to all genders.', 'jobs without experience, high paying jobs', 7, '2024-03-16', '2024-04-18 12:22:27'),
(25, 3, 'Tablets With Medicare: A Comprehensive Guide for Seniors', 'a-guide-to-medicare-tablets-for-seniors', 'The digital age has transformed how we access information, and seniors are no exception. When it comes to managing healthcare, Medicare tablets have become powerful tools, providing seniors instant access to many resources and services at their fingertips.', 'These devices offer great convenience and allow seniors to check their coverage details, schedule appointments, and manage bills on one device. This comprehensive guide will cover the numerous benefits of Medicare tablets for seniors and offer valuable tips on selecting the ideal one for their needs.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/25_iZq-e8kjXE.jpg?updatedAt=1713780735650', 3, 'Medicare Tablets: A Comprehensive Guide For Senior Health', 'Learn why Medicare tablets are essential for seniors and how to choose the best one. Get a list of Medicare Tablets offering the best features for seniors.', 'tablets, health, medical tablets', 8, '2024-03-17', '2024-04-18 12:24:45'),
(26, 4, 'Cashback Credit Cards Without Any Credit Score Restrictions', 'cash-back-credit-cards-with-no-credit-score-restrictions', 'In a finance-driven world valuing every penny saved as a penny earned, cash-back credit cards serve as vital instruments for millennials and young professionals. They are eager to boost their earnings and make savvy spending choices.', 'Traditional credit cards are being bypassed in favour of those that provide cash-back rewards, particularly ones with generous limits of £7,000 or higher and accessibility without strict credit score requirements. Let\'s discuss these financial products, highlighting four top choices.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/26_c1JDZOt9ZV.jpg?updatedAt=1713444153474', 3, '4 Best Cashback Credit Cards with ₤ 7K Limit Or More', 'Cashback credit cards with a £7,000 or higher limit and no credit score restrictions. 1. Chase Sapphire Preferred Card  2. Petal 2 Visa Credit Card, and more.', 'cashback, cashback on credit card, save money', 5, '2024-03-18', '2024-04-18 12:27:14'),
(27, 5, 'Secure Your Smartphone Today, Pay Later On Your Terms', 'secure-smartphone-today-pay-later', 'In our modern world, smartphones have evolved from mere gadgets to indispensable companions, connecting us to the digital realm, our work, and entertainment. Yet, not everyone can afford to buy one outright. What if I told you that getting the latest smartphone model is within reach without the hassle of credit checks or hefty upfront payments? It is possible. Let\'s explore the process of acquiring smartphones now and easily deferring payments, where no credit checks are needed!', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/27_SJF74Qaez.jpg?updatedAt=1713444151741', 2, 'Secure Your Desired Smartphone Now, Pay Later on Your Terms', 'Here is a revolutionary way to own the latest smartphone without credit checks or upfront payments. These easier payment methods will be your game-changer.', 'budget friendly smartphone, smartphone on emi', 4, '2024-03-19', '2024-04-18 12:29:00'),
(28, 2, 'Discover the Role and Significance of Attorneys in Society', 'discover-role-and-significance-of-attorneys-in-society', 'Understanding the intricacies of the law demands specialized expertise and skills that elude most laypeople. Attorneys prove invaluable in this area. Serving as advocates and advisors, they play a vital role in upholding the justice system.', 'In the following discussion, we seek to illuminate the diverse role of an attorney and underscore the significance of their involvement across different spheres of life. Whether you seek legal counsel as an individual, run a small business, or aspire to enter the legal field, their presence is invaluable.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/28_9KpCLUDX-O.jpg?updatedAt=1713444151483', 3, 'Exploring the Vital Role and Impact of Attorneys in Society', 'A detailed understanding of the attorney’s societal roles and importance. 1. Functions & Objectives of an Attorney • 2. Qualifications and Experience & more.', 'attorneys, impact of attorneys in society, law, importance of attorneys', 2, '2024-03-20', '2024-04-18 12:30:52'),
(29, 3, '10 Reasons Why Walk-In Tubs Are a Must-Have for Seniors', 'benefits-of-walk-in-tubs-for-seniors', 'As we get older, maintaining mobility and independence becomes increasingly important. Traditional bathtubs can pose a safety hazard for seniors due to the risk of slips and falls. Walk-in tubs offer a revolutionary solution, promoting safety and enhancing the bathing experience for seniors.', 'This blog post will cover the numerous benefits of walk-in tubs, from improved accessibility and reduced fall risk to therapeutic features. We\'ll also discuss the ability to age in place confidently and the variety of customizable options available. Let\'s discover how walk-in tubs can enhance senior health and safety, creating a more enjoyable and secure bathing experience.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/29_i17aV7Vdq.jpg?updatedAt=1713444152175', 2, 'Here’s Why Walk-In Tubs Are Essential For Seniors', 'Walk-in tubs offer long-term benefits for seniors. Discover how they promote independence, prevent falls, and contribute to a better quality of life.', 'walk-in tubs, tubs for seniors', 7, '2024-03-21', '2024-04-18 12:32:28'),
(30, 2, 'Everything You Need To Know About Plumbing Systems', 'importance-of-plumbing-systems', 'We tend to forget about the plumbing systems daily, an essential part of our lives. Plumbing quietly ensures clean drinking, cooking, and bathing water and helps us get rid of waste properly. Let\'s explore why plumbing is essential, the different kinds of systems, what plumbers do, and when we might need their help', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/30_leyH0TWwwy.jpg?updatedAt=1713444155093', 3, 'Plumbing Systems: The Importance of Regular Maintenance', 'Explore plumbing systems, including their significance, different types, the role of a plumber, and when to seek professional professional services', 'plumbing systems, maintenance of plumbing system, plumbers', 1, '2024-03-22', '2024-04-18 12:34:58'),
(31, 3, 'Ensuring Safety in Pesticide Use: A Comprehensive Guide', 'ensuring-safety-in-pesticide', 'When it comes to securing food crops and sources, pesticides serve as vital tools. However, if you overlook the safety measures while handling these chemicals, it can lead to adverse health effects and environmental harm. Therefore, it\'s crucial to grasp and implement pesticide safety protocols effectively. Let\'s explore some essential tips for using these chemicals responsibly and safely using pesticides.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/31_hUu_AYAqj.jpg?updatedAt=1713444160045', 3, 'Pesticide Safety 101: Ensuring Responsible Chemical Use', 'The secrets of pesticide safety with guidance on handling, application, and environmental consciousness. Safeguard health and nature with responsible practices.', 'pesticide safety, safe pesticide use', 3, '2024-03-23', '2024-04-18 12:37:23'),
(32, 4, 'Choosing the Best Digital Signature Software for Businesses', 'navigating-digital-signature-software-selection', 'In today\'s digital age, securing and electronically validating documents is essential. This is where digital signature software comes in. It allows you to sign documents, verify signers, and prevent tampering electronically. But with numerous options available, choosing the perfect one for your business is vital.', 'We’ll help you with just that and more. In this blog, understand the importance of digital signature software, know what to consider while selecting one, and get tips to choose the best for your business. Whether you’re a small business owner, a large corporation, or an individual looking to streamline your document management, selecting the right digital signature software can make a world of difference.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/32_Y47R6GoeLt.jpg?updatedAt=1713521474153', 2, 'Choosing the Best Digital Signature Software for Your Business', 'Explore the importance of digital signature software for businesses and gain insight into selecting the best software that meets your needs.', 'digital signature, digital signature software', 5, '2024-03-24', '2024-04-19 06:39:29'),
(33, 2, 'Cybersecurity Degrees: Unlocking a World of Potential', 'cybersecurity-degrees', 'The risk of cyber crimes and data leaks is a constant concern in today\'s digital age. This emphasizes the need for strong cybersecurity measures as individuals and businesses struggle to protect their sensitive data from cyber attackers. As a result, there is a growing demand for skilled cybersecurity experts who can combat these threats.', 'A cybersecurity degree is an excellent way for students to gain the knowledge and essential skills needed to prevent cyber crimes and pursue careers in this budding field. Here, we will explore the increasing importance of cybersecurity education, its crucial role in countering digital threats, and the various career opportunities it offers.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/33_yzfrbCfsg.jpg?updatedAt=1713521474526', 3, 'Cybersecurity Degrees: Your Path to a Safer Digital Future', 'Learn cybersecurity\'s crucial role in today’s digital world and discover the various career and education opportunities awaiting you.', 'cyber crimes, cybersecurity experts, cybersecurity degree, cybersecurity education', 7, '2024-03-25', '2024-04-19 06:41:30'),
(34, 4, 'Empowering Businesses: The Impact of Advanced Software Solutions', 'empowering-business-with-software', 'In today\'s fast-moving digital world, businesses are always looking out for ways to stay ahead, work smarter, and foster innovation. Among the most powerful tools they have at their disposal are cutting-edge software solutions. These technological marvels have completely changed the game for how companies operate, enabling them to streamline their processes, gain an edge over competitors, and make informed decisions based on data. In this exploration, we delve into how these innovative software solutions are transforming businesses and driving them towards sustained growth.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/34_230PjSEUc.jpg?updatedAt=1713521474575', 3, 'Tech-Driven Growth: How Software Solutions Propel Businesses', 'Explore how cutting-edge software solutions propel business operations, driving efficiency, innovation, and informed decision-making for sustained growth.', 'software solutions, business growth', 6, '2024-03-26', '2024-04-19 06:44:49'),
(35, 6, 'Most Trending Online Games in the World for the Year 2024', 'most-trending-online-games-in-the-world', 'In the ever-evolving realm of online gaming, trends shift as rapidly as a \"Fortnite\" leaderboard. This year has proven incredibly captivating, offering various genres that have kept gamers engaged, their anticipation high as they hover over keyboards and controllers alike.', 'The digital realm offers a vast array of experiences, ranging from intense battle royales to intricate team-based encounters. Delve into the most popular online games that have shaped this year\'s gaming scene.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/35_mESuZfGFz.jpg?updatedAt=1713521472317', 2, 'Most Trending Online Games to Watch Out for in the Year 2024', 'Explore the most trending online games in the world for 2024. 1. Fortnite • 2. Pokémon Unite • 3. Among Us • 4. FIFA series • 5. League of Legends & more.', 'trending online games, Fortnite , Pokémon, Among Us', 3, '2024-03-27', '2024-04-19 06:47:18'),
(36, 7, 'A Guide to Career Advancement in Call Center Jobs', 'call-center-jobs', 'In today\'s job market, call centers shine as places full of chances for different careers where you can talk with customers. While some might think of call center work as repeating things repeatedly, it\'s much more than that. There are many ways to move up and improve at your job. But to do that, you need to know how the industry works, be ready for any challenges, and work hard to grow your career.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/36_p6RcvzTMU.jpg?updatedAt=1713521472527', 2, 'Guiding Your Way to Success in Call Center Roles', 'Navigate the world of call center jobs, including the opportunities and the challenges to build a successful career in this fast-paced industry', 'call centre jobs, career opportunities, high paying jobs', 1, '2024-03-28', '2024-04-19 06:48:50'),
(37, 5, 'Inventive Storage Organizer Ideas to Get a Clutter-Free Home', 'inventive-storage-organizer-ideas-for-every-home', 'Many aspire to a clutter-free home where everything has its place. Yet, achieving this level of organization often demands innovative strategies. Whether you\'re a homeowner searching for intelligent ways to uphold order, an organizing enthusiast on the hunt for imaginative storage solutions, or a resident of limited space aiming to optimize every inch, you\'ll discover tailored tips below to suit your needs.', 'Discover creative storage solutions for every home for a clutter-free and stylish living space. These innovative ideas seamlessly combine form and function, bringing a touch of elegance to your home organization.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/37_1Jr5NHauY.jpg?updatedAt=1713521470946', 2, 'Inventive Storage Organizer Ideas for Every Home', 'Discover creative storage solutions to meet every home\'s needs. 1. Multi-Functional Furniture • 2. Floating Shelves • 3. Under-Stair Storage & more.', 'storage organizers, storage solutions, creative storage solutions', 8, '2024-03-29', '2024-04-19 06:50:28'),
(38, 2, 'The Ultimate Guide to Blockchain Courses for Beginners', 'beginners-guide-to-blockchain-courses', 'Blockchain technology is swiftly revolutionizing various sectors, such as finance, supply chain management, healthcare, and voting systems. This cutting-edge innovation offers a secure, transparent, and decentralized approach to storing and transferring data, making it a highly valued skill in today\'s industries.', 'Embarking on a blockchain course is a crucial initial step for those interested in exploring the potential of blockchain and establishing a foothold in this rapidly expanding field. However, with numerous options available, navigating the blockchain courses can take time and effort. In this article, we\'ll explore the basics of blockchain courses, helping you choose the one that best aligns with your career goals.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/38_ugBwyEi2N.jpg?updatedAt=1713521465229', 3, 'Unleashing the Power of Blockchain Courses for Beginners', 'Dive into the world of blockchain courses, unlock this transformative technology\'s potential, and find your path in the world of blockchain technology', 'blockchain, blockchain courses, blockchain courses for beginners', 4, '2024-03-30', '2024-04-19 06:51:51'),
(39, 2, 'Exploring the Power of Social Media Courses: Your Guide to Success Online', 'social-media-course', 'Isn’t it amazing how social media has become such a big part of our lives? From keeping up with friends to running businesses, it’s everywhere. But as we all know, with great power comes great responsibility. Welcome to the wild world of social media, it’s a place where trends come and go faster than you can say “viral” and where every like, share, and comment has the potential to make waves. But fear not, in this ever-changing digital jungle, social media courses are your trusty compass, guiding you through the twists and turns of these platforms.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/39_0wLc7TWVz.jpg?updatedAt=1713521464687', 2, 'Mastering Social Media Courses: Your Guide to Success Online', 'Unlock the secrets of social media success. Dive deep into platform dynamics, create engaging content, leverage analytics, and foster genuine connections.', 'social media courses, social media courses for beginners, mastering social media', 2, '2024-03-31', '2024-04-19 06:53:15'),
(40, 2, 'Navigating the Journey of Web Designer Courses in 2024', 'journey-of-web-designer-courses', 'Digital environments are evolving remarkably, reshaping our interactions, work dynamics, and information consumption. Web design is at the core of this evolution—an artful fusion of aesthetics and usability aimed at crafting impactful user journeys.', 'For those aspiring to become web designers, aiming for a career shift, or just wanting to refine their creative skills, thorough web designer courses light the way to digital mastery. Delving into these courses\' core elements and significant accomplishments, we guide you toward gaining a robust professional edge.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/40_K470DIO7M.jpg?updatedAt=1713521467506', 3, 'Path to Digital Excellence with Web Designer Courses', 'Discover how the web designer courses will help you gain a competitive edge in the market. 1. Understanding the Basics • 2. Mastering Design Software & more.', 'web design, web designer courses, front end development courses', 6, '2024-04-01', '2024-04-19 06:55:04'),
(41, 4, 'Mastering the Digital Landscape: Strategies for Business Growth', 'digital-marketing-strategies', 'In today\'s world, where we\'re constantly surrounded by screens, and our attention flits from one thing to another, digital marketing has become a crucial part of how businesses connect with people. It\'s like the foundation of modern business strategies, using the internet, social media, and data to change how companies interact with their audience. Let\'s take a closer look at this digital world, what makes it tick, and how it can transform a business.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/41_4MAE8hPJX.jpg?updatedAt=1713521467525', 3, 'Digital Marketing Essentials: Strategies for Business Growth', 'Discover the power of digital marketing in today\'s fast-paced world. Explore key strategies to engage your audience effectively and drive business growth.', 'digital marketing, marketing for business growth, digital marketing basics', 8, '2024-04-02', '2024-04-19 06:56:57'),
(42, 4, 'The Essential Role of CMMS in Preventive Maintenance', 'enhancing-cmms-with-preventive-maintenance', 'In fast-paced industrial operations, ensuring that machines and equipment function flawlessly is crucial for keeping production on track and avoiding costly disruptions. A sudden machinery breakdown can be a financial burden and tarnish a company\'s reputation. Employing preventive maintenance is a forward-thinking measure to prevent such expensive interruptions.', 'Nevertheless, the intricacies of administering a preventive maintenance schedule can be a task for companies juggling numerous assets. This is where leveraging the power of CMMS (Computerized Maintenance Management System) software becomes a game-changer in maintenance management. It not only reshapes maintenance procedures but also enhances productivity and sheds light on the condition of machinery.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/42_5yiLrC5_C.jpg?updatedAt=1713521464123', 2, 'Enhancing Preventive Maintenance with CMMS Software', 'Explore the advantages of using CMMS software in preventive maintenance, from streamlining workflows to automating tasks and others.', 'CMMS software, preventive maintenance', 3, '2024-04-03', '2024-04-19 07:02:57'),
(43, 4, 'Leveraging Technology for Event, CMMS, and Fleet Management', 'tech-solutions-to-drive-business-efficiency', '2024 is about a dynamic business landscape where maximizing efficiency has become essential for achieving success and maintaining a competitive edge. Embracing intelligent technological solutions tailored for specific areas such as event management, Computerized Maintenance Management Systems (CMMS), and fleet management can lead to transformative outcomes.', 'Thankfully, contemporary tech advancements provide many tools that significantly boost operational efficiency, streamline workflows, and optimize resource allocation across different sectors. Let\'s explore how modern technology can propel business efficiency forward, fostering growth and innovation.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/43_fVC7_HGRj.jpg?updatedAt=1713521465114', 3, 'Maximizing Efficiency: Technology for Events, CMMS, Fleet', 'Unlock the potential of smart solutions for events, CMMS, and fleet management to enhance your productivity and maximize efficiency today', 'smart solutions for events, CMMS, fleet management, enhance productivity ', 8, '2024-04-04', '2024-04-19 07:04:46'),
(44, 3, 'Revolutionizing Healthcare: Integrating AI Training with Patient Engagement Solutions', 'ai-training-and-healthcare', 'In our rapidly advancing world, where technological innovations are reshaping every aspect of society, the healthcare sector stands at the forefront of transformation. From specialized AI training courses for medical professionals to the adoption of patient engagement software, revolutionary changes are underway, promising a future of more personalized, efficient, and patient-centric care. In this blog, we\'ll explore how these groundbreaking developments are revolutionizing healthcare delivery, ushering in a new era of collaboration between technology and human touch.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/44_ofvngfDyo.jpg?updatedAt=1713521463825', 3, 'AI Training & Patient Engagement: Healthcare Revolution', 'Explore how AI education and patient engagement software are reshaping healthcare delivery and empowering professionals and patients for better outcomes.', 'patient engagement software, healthcare software', 1, '2024-04-05', '2024-04-19 07:06:40'),
(45, 4, 'Smart Solutions for Real Estate Management & Roofing', 'solutions-for-real-estate-management-and-roofing', 'Real estate management and roofing are experiencing a significant transformation due to the introduction of cutting-edge technologies and solutions. Previously troubled by inefficiencies and dependency on manual labor, property operations are now evolving into streamlined and highly efficient systems', 'This shift is revolutionizing how real estate managers, roofing contractors, and property owners conduct business, ultimately transforming the entire industry.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/45_JzGy1WpUd.jpg?updatedAt=1713521465567', 2, 'Smart Solutions Reshaping Real Estate & Roofing', 'These smart solutions for real estate and roofing projects will elevate your property management experience with the transformative power of technology', 'real estate, roofing, property management', 2, '2024-04-06', '2024-04-19 07:08:34'),
(46, 4, 'Boost Your Business with Automation: Web Ads, Lead Management, Marketing', 'grow-business-with-automation', 'In today\'s world, businesses are always looking for new ways to grow and stand out from the competition. It\'s not just about staying afloat but about thriving. From marketing automation to managing leads and advertising on your website, the trick is to use technology and strategy together to succeed. Let\'s talk about how you can grow your business.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/46_7L3xONEU6j.jpg?updatedAt=1713521465294', 2, 'Grow with Automation: Web Ads, Lead Management, Marketing', 'Discover how to drive business growth through web advertising, lead management, and marketing automation. Transform your engagement strategies and more.', 'Web Ads, Lead Management, Marketing', 4, '2024-04-07', '2024-04-19 07:09:43'),
(47, 3, 'The Modern Turmoil: Overcoming Cyber Challenges, Anxiety, and Embracing Industrial Progress', 'modern-problems-solutions', 'In today\'s fast-paced world, we face various challenges that can sometimes feel overwhelming. From the ever-evolving landscape of cyber threats to the pervasive presence of anxiety disorders, navigating these trials requires resilience and adaptability. However, amidst these difficulties, there are also remarkable opportunities for growth and progress, especially with the ongoing advancements in various industries. Let\'s explore how we can thrive amidst contemporary trials by confronting cyber challenges, managing anxiety, and embracing industrial advancements.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/47_Ax9zDvwaP.jpg?updatedAt=1713521464194', 2, 'Conquering Today\'s Trials: Cybersecurity, Anxiety, Industry', 'Explore different strategies for thriving in cyber challenges, anxiety issues, and industrial advancements. Learn how to navigate modern trials effectively.', 'cyber security, anxiety, anxiety issues,  industrial advancements', 1, '2024-04-08', '2024-04-19 07:18:24');
INSERT INTO `articles` (`id`, `category_id`, `title`, `url`, `description1`, `description2`, `image`, `read_time`, `meta_title`, `meta_description`, `meta_keywords`, `author_id`, `article_date`, `created_at`) VALUES
(48, 2, 'Elevate Your Professional Journey with Top MBA Skills', 'top-mba-skills', 'Staying ahead means constantly learning and growing in today\'s fast-paced business world. An MBA degree has long been seen as a way to acquire valuable skills that can lead to excellent career growth and leadership roles.', 'While MBA programs teach many skills, a few are essential for any career. Let\'s look closer at these top MBA skills and how they can help you succeed.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/48_XFXxbuiY5.jpg?updatedAt=1713529692910', 2, 'Master These Top MBA Skills for Exceptional Career Growth', 'Gain insights into the top MBA skills that matter for career growth. From leadership to adaptability, learn how these skills drive success.', 'mba courses, mba skills, career growth', 8, '2024-04-09', '2024-04-19 12:02:20'),
(49, 2, 'Enhance Confidence: Explore Excellence in Hairline Restoration', 'unveil-excellence-of-hairline-restoration', 'Confidence is your steadfast ally, the subtle force that encourages you to tackle each day. Among middle-aged adults and individuals experiencing hair loss, the state of their hairline can significantly influence this self-assurance.', 'Seeking more than just a remedy for receding hairlines or balding patterns, individuals pursue solutions for a more profound sense of confidence, not just superficial satisfaction. Explore the expertise in hairline restoration that shines in cosmetic medicine.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/49_vwUGLp7ui.jpg?updatedAt=1713529692508', 2, 'Elevate Your Confidence: Hairline Restoration Excellence', 'Unveil the excellence of hairline restoration to boost your confidence today! 1. The Basics of Hair Transplant • 2. Restoring Hairline and Appearance & more.', 'hair transplant, hair restoration, hair care, self care', 6, '2024-04-10', '2024-04-19 12:11:38'),
(50, 5, 'Simplify Your Life Using These Smart Storage Organizers', 'smart-storage-organizers', 'Life can often feel stressful, with responsibilities, possessions, and tasks that constantly come up every other day. Finding a sense of order and calm can be challenging in the middle of this chaos. But fear not—storage organizers are here, a simple solution that can help streamline your daily routines and bring harmony to your living space.', 'These simple bags and baskets offer more than tidiness; they provide a secure place for your belongings, offering peace of mind and clarity in a cluttered house.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/50_NxAvmx77o.jpg?updatedAt=1713529682521', 2, 'Optimize Your Space with Smart Storage Solutions', 'Fed up with stumbling over clutter? Explore these storage solutions, from vertical shelves to cable organizers—for a simpler, more organized life.', 'storage solutions, cable organizers', 4, '2024-04-11', '2024-04-19 12:20:50'),
(51, 4, 'The Future of Food: Exploring Careers in Manufacturing', 'future-food-manufacturing-careers', 'The food manufacturing industry is a dynamic and fascinating field, offering many job opportunities to those keen on contributing to the creation of safe, efficient, and sustainable food products. With the population on a steady rise, there is an increasing demand for inventive food production techniques, which makes this the perfect time to explore a career in this industry. Let’s dive into the world of food manufacturing and learn about the varied opportunities awaiting exploration.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/51_XbWRhg-mKS.jpg?updatedAt=1713529680313', 2, 'The Future of Food Manufacturing & the Growing Careers', 'Discover the growing career opportunities in the food manufacturing industry and learn the skills you need to succeed in this dynamic field.', 'career in food, food manufacturing', 2, '2024-04-12', '2024-04-19 12:22:20'),
(52, 1, 'A Beginner\'s Guide to Choosing the Best Cloud Storage', 'how-to-choose-the-best-cloud-storage', 'In the current digital era, information is paramount. Yet, as data requirements continue to grow, the constraints of local storage persistently challenge us. Here is where cloud storage steps in—a technology revolutionizing data storage, access, and management.', 'Cloud storage has become a crucial tool for individuals and businesses, providing flexibility, scalability, and efficiency. If you\'re seeking a comprehensive and secure storage solution, Cloud Storage might be just what you need. This blog aims to explain its concept and functionality and aid you in selecting the most suitable option for your needs and business.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/52_aXXsY39DI.jpg?updatedAt=1713529680890', 3, 'Tips for Finding the Perfect Cloud Storage Solution', 'Learn to choose the perfect cloud storage service, find the best solution for your needs, and keep your data secure anytime and anywhere.', 'cloud storage, cloud storage solution', 3, '2024-04-13', '2024-04-19 12:23:50'),
(53, 5, 'The Ultimate Guide to Enjoying All-Inclusive Vacations', 'a-guide-to-all-inclusive-vacations', 'Are you dreaming of a vacation where every detail, from lodging and meals to exploration and entertainment, is handled? Or do you desire relaxation without worrying about budgeting for every aspect of your trip? You must definitely look for “All-inclusive vacations.” This demanding, popular travel provides a stress-free way to explore the world, allowing you to relax and focus solely on creating unforgettable memories.', 'From luxurious accommodations to gourmet dining activities, all-inclusive packages escape the everyday grind. Whether you\'re searching for romance, family fun, or solo adventure, these vacations cater to every preference for a seamless blend of luxury and comfort. Today, we\'ll dig into the world of all-inclusive holidays, discussing their benefits, popular destinations, and tips for planning your dream vacation.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/53_v561SicBWV.jpg?updatedAt=1713529681718', 3, 'Elevate Your Travel Experience with All-Inclusive Vacations', 'Discover the ultimate guide to all-inclusive vacations, elevate your travel experience, and find tips for planning your dream getaway seamlessly.', 'travel, dream getaway, vacation', 5, '2024-04-14', '2024-04-19 12:25:24'),
(54, 2, 'Navigating Tomorrow: Embracing Online Degrees in the Digital Era', 'online-degree-in-digital-era', 'In this rapidly evolving landscape of education, online degrees are emerging as powerful tools for learners worldwide. With the advent of technology, traditional boundaries are fading, and opportunities for education are expanding like never before. In this blog, we\'ll explore how online degrees are shaping the future of education in the digital age, offering accessibility, flexibility, and innovation to learners everywhere.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/54_KVC29eXfS-.jpg?updatedAt=1713529677601', 2, 'Virtual Visions: Online Degrees Developing Digital Era', 'Unlock the doors to a flexible and accessible future with online degrees in this digital era. Embrace innovation and redefine your learning journey today.', 'online degrees, distance learning', 6, '2024-04-15', '2024-04-19 12:27:14'),
(55, 7, 'The Process Of Career Shifts: Your Guide to Master Moving Job', 'moving-jobs', 'Looking for a new job can make you feel excited and exhausted at the same time. Whether you\'re transitioning out of necessity or seeking growth opportunities, learning how to transition your job properly is essential for a successful career path. In this guide, we\'ll explore some practical strategies to look into changing jobs smoothly and confidently.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/55_LaC4uGt4K.jpg?updatedAt=1713529681763', 2, 'Career Crossroads: Your Guide to Moving Job Successfully ', 'Discover essential strategies for mastering job transitions with our comprehensive guide. Learn how to change jobs confidently and advance your career smoothly.', 'career change, move job, job transitions', 7, '2024-04-16', '2024-04-19 12:28:41'),
(56, 4, 'Understanding Steel Supply: Exploring the Ins and Outs', 'steel-supply', 'Steel, the steadfast companion of modern construction and industry, holds a story beyond its gleaming facade. Steel goes from being a raw material to a finished product through a complex supply chain that shapes skylines and underpins economies. In this exploration, we\'ll unravel the intricacies of steel supply, shedding light on the factors driving its dynamics. From global demand shifts to the sourcing of raw materials, each aspect plays a pivotal role in defining the availability and affordability of this vital resource. Join us as we delve into the heart of the steel industry, where every beam tells a tale of resilience and innovation.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/56_aMbDlo0gG.jpg?updatedAt=1713529681399', 2, 'Steel Supply Challenges: Know The Ins And Outs Of Industries', 'Dive into the world of steel supply, the dynamics of global demand, raw material sourcing, trade tariffs, environmental regulations, and sustainability.', 'steel supply, raw material, steel demand', 4, '2024-04-17', '2024-04-19 12:30:13'),
(57, 7, 'Exploring Future Pathways and Opportunities in Food Packing Careers', 'food-packing', 'In the bustling world of food production, there\'s a crucial role that often goes unnoticed: food packing. Have you ever wondered about the people behind those neatly wrapped packages on grocery store shelves? Food packing professionals ensure our snacks, meals, and treats reach us safely and in perfect condition. Let\'s take a closer look at the world of food packing jobs, the diverse opportunities available, and the pathways to enter this fulfilling career.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/57_PxEzdttkq.jpg?updatedAt=1713529680780', 2, 'Discover the Opportunities and Career in Food Packing', 'Discover the world of food packing careers, including designing, sustainability, engineering, and other diverse opportunities in this thriving industry.', 'food packaging careers, sustainable packaging, packaging techniques', 5, '2024-04-18', '2024-04-19 12:32:01'),
(58, 5, 'Transforming Your Home: The Power of Soft Couches & Sofas', 'comfort-of-couches-and-sofas', 'When turning a house into a home, one of the first things we consider is comfort. Couches or sofas play a significant role in providing this comfort. They\'re not just seats; they\'re where we relax after a tiring day, gather with family and friends for chats, and enjoy cozy moments with a book or movie. Let\'s explore everything about couches and sofas, where comfort meets style, and each design choice has its own story.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/58_ZNuSEdwqCr.jpg?updatedAt=1713529681756', 2, 'Enhancing Comfort: The Beauty of Soft Couches and Sofa', 'Explore the evolution of soft couches and sofas, their diversity in design, material choices, customization options, and multi-functional qualities.', 'sofas, couches, soft couches and sofas', 1, '2024-04-19', '2024-04-19 12:34:00'),
(59, 4, 'Nurturing Success By Fostering Leadership and Fueling Business Growth', 'fueling-business-growth', 'In the dynamic landscape of business, growth isn\'t just about numbers; it\'s about cultivating leadership and securing the resources needed to thrive. Empowering growth in today\'s business landscape requires a multifaceted approach that prioritizes both leadership development and strategic funding. Leadership development and securing funding are two pillars crucial to empowering growth. Let\'s delve into how these aspects intertwine to pave the way for success in business ventures.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/59_gOVfNF5iMc.jpg?updatedAt=1713529679967', 2, ' Achieve Growth By Leadership Development & Business Funding', 'Discover how effective leadership development and strategic business funding intersect to empower growth. Know the keys to success in the competitive landscape.', 'leadership development, strategic business funding', 6, '2024-04-20', '2024-04-19 12:35:37'),
(60, 4, 'Revolutionize Your Real Estate Business with Innovation', 'real-estate-business', 'In the fast-changing world of real estate, innovation is the key. Customer Management Software (CMS) and Prefabricated Buildings are two revolutionary solutions that are making headlines. These technologies aren\'t just shaking things up; they\'re transforming the entire industry landscape, paving the way for improved efficiency, sustainability, and customer happiness.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/60_beCqhitrX.jpg?updatedAt=1713529681709', 3, 'Streamline Your Real Estate Business with Innovative Methods', 'Unleash your real estate business\'s full potential by implementing innovative strategies to enhance productivity, efficiency, and profitability.', 'real estate business, innovative strategies to enhance productivity, enhance efficiency', 3, '2024-04-21', '2024-04-19 12:37:03'),
(61, 4, 'Path to Achieving Mastery in Forex Trading for Financial Freedom', 'master-in-forex-trading', 'The world of Forex trading, a sophisticated interplay of currency transactions, shines as a guiding light for individuals striving for financial autonomy.', 'It stands as the world\'s largest financial marketplace, where determination, a solid educational grounding, savvy use of technology, and strategic insight converge to unlock opportunities for both novices and seasoned traders. Our guide delineates the steps to become proficient in Forex trading.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/forex_trading2_snZXrHECr5.jpg?updatedAt=1714724815881', 2, 'Master Forex Trading for Financial Independence', 'Master the forex trading for financial freedom. 1. The Basics of Forex Trading • 2. Leveraging Technology • 3. Strategy Development, and more.', 'forex', 2, '2024-05-02', '2024-05-03 08:18:41'),
(62, 3, 'A Beginner’s Guide to Understanding Depression Tests', 'understanding-depression-tests', 'Depression is more than just feeling down on a bad day. It\'s a serious mental health condition that affects millions worldwide. But how can someone understand if what they’re experiencing is depression or just a passing phase? Depression tests offer a practical first step in recognizing mental health concerns.', 'This guide will explain depression tests, how they work, and why they’re essential for both personal insight and professional guidance. Whether you’re exploring mental health for yourself or a loved one, this knowledge could be your first step toward finding clarity and support.', 'https://ik.imagekit.io/gku4adhog/browsehunt/A_Beginners_Guide_to_Understanding_Depression_Tests/A_Beginners_Guide_to_Understanding_Depression_Tests-min.jpg?updatedAt=1733296545558', 2, 'Your Guide to Understanding Depression Tests', 'Learn what depression tests are, how they work, and how they can help individuals detect symptoms early and seek appropriate mental health support.', 'depression', 2, '2024-12-01', '2024-12-04 09:59:07'),
(63, 5, 'HVAC Companies Near Me: A Guide to Making the Best Choice', 'hvac-companies-near-me', 'Your HVAC system is the backbone of your home’s comfort, ensuring year-round temperature control and air quality. Choosing the right HVAC company near you becomes critical when your system needs repair or maintenance. The market has multiple options, each promising exceptional service, but how do you separate the best from the rest? ', 'In this blog, we will provide the essential steps to identify the perfect match for your needs—considering certifications, experience, and customer satisfaction. With these insights, you can secure an HVAC provider that offers peace of mind and keeps your home running smoothly through every season.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/63_Kx5w6cGLQ.jpg?updatedAt=1733896306374', 3, 'HVAC Companies Near Me: Your Guide to Finding the Best Service', 'Let our guide help you choose the perfect HVAC service provider and quickly locate reliable HVAC companies near you. ', 'HVAC', 3, '2024-12-11', '2024-12-11 05:36:08'),
(64, 7, 'Understanding the Path to a Successful Plumbing Job', 'understanding-the-path-to-a-successful-plumbing-job', 'Are you considering starting a career in plumbing or simply keen to take on simple household plumbing fixes? No matter the reason, plumbing is an essential skill to learn. Plumbing is a crucial task that ensures our water systems function efficiently. Here, we explain what plumbing involves, its significance, and the steps to make this essential life skill a successful career choice.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/64_sLwYVxRh1.jpg?updatedAt=1733896306373', 3, 'The Path to a Successful Plumbing Job', 'Understand plumbing with insights on skills, tools, importance, and safety. Start your plumbing career today!', 'Plumbing', 4, '2024-12-11', '2024-12-11 05:37:55'),
(65, 7, 'Forklift Jobs: Everything You Need to Know ', 'forklift-jobs ', 'Looking for a stable, rewarding career with plenty of room for growth? Forklift jobs might be the opportunity you\'ve been searching for. Vital across industries like manufacturing, warehousing, logistics, and retail, these roles are essential for ensuring operations run smoothly. With the rise of e-commerce and global supply chains, the demand for skilled forklift operators is on the rise.', 'In this blog, we will discuss the benefits of forklift jobs, their requirements, tips for getting started, and why this could be a great career choice for you. ', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/65_evpYIji98.jpg?updatedAt=1733896306464', 2, 'Forklift Operator Jobs: Everything You Need to Know', 'Discover the benefits of forklift jobs. Get tips on training, growth opportunities, and how to advance as a forklift operator.  ', 'Forklift Jobs ', 5, '2024-12-11', '2024-12-11 05:39:13'),
(66, 7, 'Electrician Jobs: A Guide to Building a Rewarding Career', 'electrician-jobs', 'Electrician jobs rank among the most desirable careers in today’s ever-evolving job market. As the demand for skilled tradespeople continues to rise, a career as an electrician provides financial security, job fulfillment, and ample opportunities for advancement. In this blog, we will inform aspiring electricians about the many advantages of pursuing this career and offer valuable guidance on how to get started in the field.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/66_Lf9U7YP0I.jpg?updatedAt=1733896306471', 2, 'Electrician Jobs: A Roadmap to Building a Rewarding Career', 'Explore how electrician jobs provide excellent career opportunities with competitive salaries, strong job satisfaction, and room for growth. Find out more now!', 'Electrician', 6, '2024-12-11', '2024-12-11 05:40:26'),
(67, 7, 'Trabajos de Limpieza de Oficinas: $43/Hora sin Experiencia', 'trabajos-de-limpieza-de-oficinas-a-43-dolares-la-hora-sin-experiencia', 'Los trabajos de limpieza de oficinas pueden parecer tareas rutinarias que nunca terminan. Pero si miras más de cerca, verás que es una industria en crecimiento con oportunidades laborales emocionantes y muchos beneficios.', 'Ya sea que estés comenzando tu carrera, estés considerando un cambio o tengas curiosidad sobre la industria, este blog arrojará luz sobre varias perspectivas y ofrecerá información valiosa para ayudarte a crecer y avanzar.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/67_I3Xn9Es4D.jpg?updatedAt=1733896306223', 3, 'Trabajos de Limpieza de Oficinas: $43/Hora sin Experiencia', 'Gane $ 43 por hora en trabajos de limpieza de oficinas sin experiencia y ayude a mantener los espacios de trabajo limpios y ordenados.', 'Office Cleaning Jobs', 7, '2024-12-11', '2024-12-11 05:42:29'),
(68, 5, 'Apartamentos de 2 Dormitorios | Ubicación Ideal | Desde $350/Mes', 'apartamentos-de-dos-dormitorios-en-ubicación-central', '¿Estás buscando un apartamento de dos habitaciones lujoso, acogedor y conveniente en una ubicación privilegiada? Ahora puedes rentar uno en zonas céntricas con increíbles beneficios para tu estilo de vida por solo $350/mes. Estos apartamentos en ubicaciones estratégicas ofrecen la combinación perfecta de sofisticación, comodidad y accesibilidad, lo que los hace ideales para vivir en la ciudad. ', 'En este blog, exploraremos por qué estos apartamentos de dos habitaciones se destacan y cómo redefinen la vida moderna.', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/68_CStb-Zcn_.jpg?updatedAt=1733896306480', 3, 'Departamentos de 2 Habitaciones | Gran Ubicación | Desde $350/Mes', 'Encuentra tu apartamento ideal de 2 habitaciones con dormitorios acogedores, baños de estilo spa y ubicaciones privilegiadas en la ciudad. ¡Desde $350/mes!', 'Apartment (2 bedroom apartment)', 8, '2024-12-11', '2024-12-11 05:44:30'),
(69, 7, 'Comprender el Camino hacia un Trabajo Exitoso en Plomería', 'comprender-el-camino-hacia-un-trabajo-exitoso-en-plomeria', '¿Estás considerando iniciar una carrera en plomería o simplemente interesado en realizar reparaciones básicas en el hogar? Sea cual sea la razón, la plomería es una habilidad esencial para aprender. Este oficio es crucial para garantizar que nuestros sistemas de agua funcionen eficientemente. Aquí, explicamos en qué consiste la plomería, su importancia y los pasos para convertir esta habilidad esencial en una carrera exitosa.', '', 'https://ik.imagekit.io/syin0m2gb/browse-hunt/69_GFy3_HehW.jpg?updatedAt=1733896306234', 2, 'El Camino hacia un Trabajo Exitoso en Plomería', 'Comprende la plomería con información sobre habilidades, herramientas, importancia y seguridad. ¡Comience su carrera de plomería hoy!', 'Plumbing', 1, '2024-12-11', '2024-12-11 05:45:49');

-- --------------------------------------------------------

--
-- Table structure for table `authors`
--

CREATE TABLE `authors` (
  `id` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

--
-- Dumping data for table `authors`
--

INSERT INTO `authors` (`id`, `name`) VALUES
(1, 'James Smith'),
(2, 'Shiro Hernandez'),
(3, 'Kevin James'),
(4, 'Evelyn Wang'),
(5, 'Jim Swede'),
(6, 'Percy Cooper'),
(7, 'Nico ZUcker'),
(8, 'Olivia Sakai');

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `id` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `icon` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `meta_title` varchar(255) DEFAULT NULL,
  `meta_description` varchar(255) DEFAULT NULL,
  `meta_keywords` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`id`, `name`, `description`, `image`, `icon`, `url`, `meta_title`, `meta_description`, `meta_keywords`, `created_at`) VALUES
(1, 'Technology', 'Where Innovation Meets Possibility', NULL, NULL, 'technology', 'Tech Reviews | Findmyresponse', 'Discover the latest in technology with insightful reviews and comparisons on Findmyresponse. Make informed decisions on gadgets, devices, and more.', NULL, '2024-04-12 12:58:33'),
(2, 'Education', 'Empowering Minds to Illuminate Futures', NULL, NULL, 'education', 'Education Reviews: Insightful Analysis & Recommendations', 'Explore insightful education reviews on FindMyResponse. Discover the best resources, courses, and institutions for your learning journey.', NULL, '2024-04-12 12:59:19'),
(3, 'Health', 'Good Health Starts with Consistent Choices', NULL, NULL, 'health', 'Health Reviews | Findmyresponse', 'Findmyresponse offers comprehensive health reviews. Explore wellness products, expert advice, and user insights to support your well-being decisions.', NULL, '2024-04-12 12:59:45'),
(4, 'Business', 'Maximizing Profit through Strategic Innovation', NULL, NULL, 'business', 'Business Reviews | Findmyresponse', 'Get informed about the latest in business. FindMyResponse offers unbiased reviews and insights to help you navigate the world of commerce effectively.', NULL, '2024-04-12 12:59:45'),
(5, 'Lifestyle', 'Where Every Choice Reflects Your Actions', NULL, NULL, 'lifestyle', 'Lifestyle Reviews | Findmyresponse', 'Explore lifestyle reviews on Findmyresponse. Find insights and recommendations to enhance your day-to-day living, from fashion to wellness.', NULL, '2024-04-12 13:00:41'),
(6, 'Entertainment', 'Where Imagination Meets Reality', NULL, NULL, 'entertainment', 'Entertainment Reviews | Findmyresponse', 'Discover the latest in entertainment on Findmyresponse. Explore reviews, recommendations, and insights on movies, music, games, and more.', NULL, '2024-04-12 13:50:25'),
(7, 'Jobs', 'Real Experiences, Informed Decisions & Better Futures', NULL, NULL, 'jobs', 'Job Reviews | Findmyresponse', 'Explore comprehensive job reviews on Findmyresponse. Real insights, real experiences, making your career choices easier. Find your perfect fit now!', NULL, '2024-04-17 10:48:22');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin_master`
--
ALTER TABLE `admin_master`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `articles`
--
ALTER TABLE `articles`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `authors`
--
ALTER TABLE `authors`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin_master`
--
ALTER TABLE `admin_master`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT for table `articles`
--
ALTER TABLE `articles`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=70;

--
-- AUTO_INCREMENT for table `authors`
--
ALTER TABLE `authors`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
